[package]
name = "imp"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1" }
thiserror = { version = "2" }
tokio = { version = "1" }

[dependencies]
imp_kernel = { path = "crates/imp_kernel" }

anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
