[package]
name = "imp"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
chrono = { version = "0.4" }
eframe = { version = "0.29", features = ["default"] }
egui_extras = { version = "0.29", features = ["default"] }