[package]
name = "imp_ddd_derive"
version = "1.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
#proc-macro2 = { version = "1" }
quote = { version = "1" }
syn = { version = "2", features = ["extra-traits"] }
